services:
  - type: web
    name: reservation-project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd reservation_project && gunicorn reservation_project.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: reservation-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*"

databases:
  - name: reservation-db
    plan: free
    databaseName: reservation_db
    user: reservation_user
